server:
  port: 8084

spring:
  application:
    name: donation-service
  datasource:
    url: jdbc:postgresql://postgres-db/hugnet_donations
    username: postgres
    password: 5511442233
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
logging:
  level:
    org.springframework: INFO

# Clave secreta para firmar los JWT
jwt:
  secret: VW5hQ2xhdmVTZWNyZXRhTXV5TGFyZ2FZQ29tcGxlamFQYXJhTWlQcm95ZWN0b0h1Z05ldDIwMjU=

# Configuraci√≥n de HugNet
mercadopago:
  access:
    token: APP_USR-4855517684274631-111917-b9007c1a327668180c1f3ce86f6f5b69-3003627325