server:
  port: 8083

spring:
  application:
    name: sponsor-service
  datasource:
    url: jdbc:postgresql://postgres-db/hugnet_sponsors
    username: postgres
    password: 5511442233
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

# Clave secreta para firmar los JWT
jwt:
  secret: VW5hQ2xhdmVTZWNyZXRhTXV5TGFyZ2FZQ29tcGxlamFQYXJhTWlQcm95ZWN0b0h1Z05ldDIwMjU=